"""Add comprehensive football statistics fields

Revision ID: b5ce6cdd13d5
Revises: 2d8789250ec8
Create Date: 2025-07-30 15:33:38.133091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5ce6cdd13d5'
down_revision = '2d8789250ec8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('career_passing_completions', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('career_passing_attempts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('career_passing_touchdowns', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('career_rushing_attempts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('career_rushing_touchdowns', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('career_receptions', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('career_receiving_touchdowns', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('career_passes_defensed', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('career_fumbles', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('career_fumbles_lost', sa.Integer(), nullable=True))

    with op.batch_alter_table('player_game_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passing_completions', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('passing_attempts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('passing_touchdowns', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rushing_attempts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rushing_touchdowns', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('receptions', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('receiving_targets', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('receiving_touchdowns', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('passes_defensed', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fumbles', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fumbles_lost', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('field_goals_attempted', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('extra_points_attempted', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_game_stats', schema=None) as batch_op:
        batch_op.drop_column('extra_points_attempted')
        batch_op.drop_column('field_goals_attempted')
        batch_op.drop_column('fumbles_lost')
        batch_op.drop_column('fumbles')
        batch_op.drop_column('passes_defensed')
        batch_op.drop_column('receiving_touchdowns')
        batch_op.drop_column('receiving_targets')
        batch_op.drop_column('receptions')
        batch_op.drop_column('rushing_touchdowns')
        batch_op.drop_column('rushing_attempts')
        batch_op.drop_column('passing_touchdowns')
        batch_op.drop_column('passing_attempts')
        batch_op.drop_column('passing_completions')

    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_column('career_fumbles_lost')
        batch_op.drop_column('career_fumbles')
        batch_op.drop_column('career_passes_defensed')
        batch_op.drop_column('career_receiving_touchdowns')
        batch_op.drop_column('career_receptions')
        batch_op.drop_column('career_rushing_touchdowns')
        batch_op.drop_column('career_rushing_attempts')
        batch_op.drop_column('career_passing_touchdowns')
        batch_op.drop_column('career_passing_attempts')
        batch_op.drop_column('career_passing_completions')

    # ### end Alembic commands ###
