"""Add enhanced PlayerGameStats columns

Revision ID: e73522c41890
Revises: 2d8789250ec8
Create Date: 2025-07-30 14:30:27.460881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e73522c41890'
down_revision = '2d8789250ec8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_game_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passing_touchdowns', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rushing_touchdowns', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('receiving_touchdowns', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('field_goals_attempted', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fumbles', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fumbles_lost', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('completions', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('pass_attempts', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_game_stats', schema=None) as batch_op:
        batch_op.drop_column('pass_attempts')
        batch_op.drop_column('completions')
        batch_op.drop_column('fumbles_lost')
        batch_op.drop_column('fumbles')
        batch_op.drop_column('field_goals_attempted')
        batch_op.drop_column('receiving_touchdowns')
        batch_op.drop_column('rushing_touchdowns')
        batch_op.drop_column('passing_touchdowns')

    # ### end Alembic commands ###
